### ISSUE TITLE
Export types

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres-meta#126]
# Chore

## Describe the chore

I was trying to use the `PostgresTable` type within Supabase Studio - it would be awesome if we can expose all of the types so that we can use them in the npm package

**Comment by kiwicopple** [comment]
@soedirgo - thoughts on this one? Any preference which [types](https://github.com/supabase/postgres-meta/blob/develop/src/lib/index.ts) to expose?

**Comment by soedirgo** [comment]
I think for starters we should export the types in [`types.ts`](https://github.com/supabase/postgres-meta/blob/develop/src/lib/types.ts) - these seem to be the most useful ones.

**Comment by xerosanyam** [comment]
I'd like to take this one.

**Comment by kiwicopple** [comment]
Go for it @xerosanyam

**Comment by Strift** [comment]
Hello :wave: I saw this issue was labeled "good first issue" so I made a PR #130 

It's my first PR and I'm just starting with TS, so I hope I've done it right. :sweat_smile: 

Cheers,

**Comment by xerosanyam** [comment]
@Strift no worries at all.
