### ISSUE TITLE
bug: fix function return type

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres-meta#132]
# Chore

## Describe the chore

Looks like it's `return_type` here: 

https://github.com/supabase/postgres-meta/blob/b139fd6eb5564258fc073da49ad6ecee78bb3984/src/lib/types.ts#L80

But `rettype` here:

https://github.com/supabase/postgres-meta/blob/b139fd6eb5564258fc073da49ad6ecee78bb3984/src/lib/PostgresMetaFunctions.ts#L83

**Comment by soedirgo** [comment]
Shouldn't be a bug since `return_type` is for `retrieve` and `rettype` is for `create`, but yeah better for it to be consistent. @w3b6x9 thoughts?

**Comment by kiwicopple** [comment]
yeah technically just a chore but also wanted to catch it before it's a breaking change (which I guess it is already)

**Comment by w3b6x9** [comment]
@soedirgo yep, agree on keeping it consistent. 

@kiwicopple mentioned to make the change from `rettype` to `return_type` to make it clearer so I'll make a PR and ping @soedirgo.

**Comment by soedirgo** [comment]
Fixed in #133 👍
