### ISSUE TITLE
Support for Views

### ISSUE THREAD

**Issue by phamhieu** [supabase/postgres-meta#141]
# Feature request

## Is your feature request related to a problem? Please describe.

This is something we need for the dashboard. 

At least, get all views, we only show view right now on the table editor. Right now, we pulling postgREST open api, then filter out  the tables on OpenApi definitions to get views; very hacky

**Comment by kiwicopple** [comment]
this code is likely to be:

```
select schemaname as schema, viewname as name from pg_catalog.pg_views
      where schemaname NOT IN ('pg_catalog', 'information_schema')
      order by schemaname, viewname; 
```
