### ISSUE TITLE
Support for enums

### ISSUE THREAD

**Issue by phamhieu** [supabase/postgres-meta#142]
# Feature request

## Is your feature request related to a problem? Please describe.

This is something we need for the dashboard. We need to get all available enums type. 

## Additional context
Right now we have to run multiple queries to retrieve available enums with it values.

Retrieve all enum types
`SELECT "oid" as "id", "typname" as "name" FROM pg_type WHERE typcategory = 'E';`

Retrieve enum values base on id
`SELECT enumlabel FROM pg_enum WHERE enumtypid = ${enumID};`

**Comment by soedirgo** [comment]
This should be possible with the `/types` endpoint, but might need to check whether or not the `enums` prop exists to filter for only enums:
```json
[
  {
    "id": 16385,
    "name": "user_status",
    "schema": "public",
    "format": "user_status",
    "enums": [
      "ACTIVE",
      "INACTIVE"
    ],
    "comment": null
  },
  {
    "id": 16439,
    "name": "meme_status",
    "schema": "public",
    "format": "meme_status",
    "enums": [
      "new",
      "old",
      "retired"
    ],
    "comment": null
  }
]
```
