### ISSUE TITLE
Consider adding support for propagating messages and errors

### ISSUE THREAD

**Issue by darora** [supabase/postgres-meta#153]
https://www.postgresql.org/docs/13/plpgsql-errors-and-messages.html
https://node-postgres.com/api/client#events (notice, etc)

**Comment by soedirgo** [comment]
Just looked into this and apparently it can only log `NOTICE`, not `WARNING`, `INFO`, etc.:
- https://github.com/brianc/node-postgres/issues/1216
- https://github.com/brianc/node-postgres/issues/1544

Seems to be of limited use - I'll revisit once there's a way to handle all log levels.
