### ISSUE TITLE
Column should has is_updatable false with GENERATED ALWAYS 

### ISSUE THREAD

**Issue by phamhieu** [supabase/postgres-meta#163]
# Bug report

## Describe the bug

Related to https://github.com/supabase/grid/issues/85

```
// When a column is defined with GENERATED ALWAYS like
ALTER TABLE tablename
    ADD COLUMN fts tsvector
               GENERATED ALWAYS AS (to_tsvector('english', "columnname")) STORED;


// or
id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY;
```

pg-meta should return the column info with `is_updatable = false`.

**Comment by soedirgo** [comment]
I think the name's a bit confusing here - `is_updatable` is meant for FDW columns/tables (https://github.com/postgres/postgres/commit/dc3eb5638349e74a6628130a5101ce866455f4a3).

For filtering based on `GENERATED ALWAYS` you can instead use `identity_generation: "ALWAYS"`, but let me know if that doesn't cut it

**Comment by soedirgo** [comment]
Scratch that, looks like it's mostly relevant for updatable views:
- https://www.postgresql.org/docs/current/sql-createview.html#id-1.9.3.97.7.6.2
- https://www.postgresql.org/docs/current/infoschema-columns.html
- https://hasura.io/blog/the-pros-and-cons-of-updatable-views/

Either way the meaning is different I think - for `GENERATED ALWAYS` you can do:
```sql
-- CREATE TABLE t(id int8 GENERATED ALWAYS AS IDENTITY PRIMARY KEY);
INSERT INTO t (id) VALUES (DEFAULT);
-- or
UPDATE t SET id = DEFAULT; -- updates `id`s to newly generated values
```

**Comment by phamhieu** [comment]
For your context:
- on @supabase/grid on a row updated, i receive back a new row json
- I use `json_populate_record` to create query updating that row json

```
// I can check and ignore primary key from json_populate_record query
id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY;

// I have no way to know if this column is defined as GENERATED ALWAYS to ignore from update query
ALTER TABLE tablename
    ADD COLUMN fts tsvector
               GENERATED ALWAYS AS (to_tsvector('english', "columnname")) STORED;
```

```
update public.test_tsvector set (text,fts) = (select text,fts from json_populate_record(null::public.test_tsvector, E'{\"text\":\"hello world 123\\\\n\",\"fts\":\"''hello'':1 ''world'':2\"}')) where id = 1;
=> error: {"error":{"code":400,"message":"column \"fts\" can only be updated to DEFAULT"}}
```

Any idea how can we recognize a `GENERATED ALWAYS` column? @soedirgo

**Comment by soedirgo** [comment]
> Any idea how can we recognize a GENERATED ALWAYS column?

Should be able to get it from `identity_generation`, the value is `"ALWAYS"` if it is

**Comment by phamhieu** [comment]
It will not return from `identity_generation ` if the column is not IDENTITY
![Screenshot 2021-11-29 at 1 34 16 PM](https://user-images.githubusercontent.com/689843/143819673-0c5cf79d-0f48-41f9-a404-88ac29809224.png)

**Comment by soedirgo** [comment]
Hmm gotcha, I can add another property `is_generated` to account for generated columns.

**Comment by soedirgo** [comment]
#164 is a quick fix to allow retrieving `is_generated: boolean`, but let me know if you need support for `POST`/`PATCH` (needs more thought)
