### ISSUE TITLE
`DATE`s are returned as JS `Date`s

### ISSUE THREAD

**Issue by soedirgo** [supabase/postgres-meta#174]
Context: https://github.com/supabase/supabase/issues/4076

**Comment by burggraf** [comment]
There's another issue similar to this one in the system.  I'll try to find it and link it.

**Comment by burggraf** [comment]
You already linked one of them I was thinking of: 
 https://github.com/supabase/supabase/issues/4076

This might be somewhat relevant?  https://github.com/supabase/postgrest-js/issues/217

**Comment by soedirgo** [comment]
Thanks! The other one is postgrest-js specific, but may be supported by typegen (which is a separate issue I think).
