### ISSUE TITLE
pg_authid dependency makes using managed postgres impossible

### ISSUE THREAD

**Issue by SuiOni** [supabase/postgres-meta#212]
# Bug report

## Describe the bug

After a lot of time settingup AWS RDS Postgres the final thing that prevents a working instance is that pg-meta is using pg_authid which is not available for AWS RDS and most manageged Postgres Instances. 
pg_roles has all the needed columns except passwords.

Can we replace pg_authid with pg_roles? 
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use AWS RDS Postgress as DB.
2. Open Supabase Studio
3. Click on Tables

## Expected behavior

Working Studio

## System information

- OS: [AWS EC2 and RDS]
- Version of supabase-js: [e.g. 6.0.2]

## Additional context

![Bildschirmfoto 2022-03-25 um 21 07 07](https://user-images.githubusercontent.com/4796498/160193765-a3d593b2-bf0d-4174-a63a-d444667ae134.png)

**Comment by soedirgo** [comment]
> Can we replace pg_authid with pg_roles?

+1, we should be using pg_roles from the start. Would you be willing to make a PR for this?

**Comment by fuergaosi233** [comment]
> > Can we replace pg_authid with pg_roles?
> 
> +1, we should be using pg_roles from the start. Would you be willing to make a PR for this?

Can you review this PR? It works OK for me locally.
