### ISSUE TITLE
Type error: Don't use `{}` as a type

### ISSUE THREAD

**Issue by probablykasper** [supabase/postgres-meta#332]
# Bug report

## Describe the bug

With v2 I get this error after having generated types, probably because of TS strict mode:
```
Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.
```

due to the generated types including this:
```ts
export interface Database {
		Functions: {}
	}
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

TypeScript strict mode probably needs to be enabled.
Run `supabase gen types typescript --local > databaseDefinitions.ts`

## System information

- OS: macOS
- Version of supabase-js: 2.0.0-rc.6
- Version of Node.js: 16.15.0

**Comment by soedirgo** [comment]
The error seems to be coming from typescript-eslint. What do you suggest the replacement should be? `Record<string, never>` is not exactly correct, see https://github.com/microsoft/TypeScript/issues/47486#issuecomment-1015671856

**Comment by probablykasper** [comment]
I don't really see why `Record<string, never>` doesn't fit. It doesn't seem like it's supposed to have any properties, so why would you ever need to access it's properties?

**Comment by soedirgo** [comment]
It needs to give a TS error when accessing a property, whereas `Record<string, never>` allows accessing properties (with value of type `never`).

**Comment by soedirgo** [comment]
Actually, `Record<never, never>` seems to work. It resolves to `{}` but seems to fool ts-eslint somehow.
