### ISSUE TITLE
Get 404 if use colume.ts

### ISSUE THREAD

**Issue by fuergaosi233** [supabase/postgres-meta#397]
# Bug report

## Describe the bug

If i use colume.ts , all of router will register failed and no error.

## To Reproduce

1.  start server
2. request localhost:1337/schemas
3. get 404 and see log
<img width="638" alt="image" src="https://user-images.githubusercontent.com/22197568/196704220-9661e8f2-9df4-49de-803a-9c8fbc4f6e34.png">
<img width="530" alt="image" src="https://user-images.githubusercontent.com/22197568/196704656-2ac179d2-d03f-473e-9e95-6cd430f7959e.png">
4. comment this code block
<img width="958" alt="image" src="https://user-images.githubusercontent.com/22197568/196704779-0ec8babc-8d11-459e-895c-de992300e024.png">

5. it's fine

## System information

- OS: Linux
- Browser (if applies) Chrome
- Version of Node.js: Node.js v16.16.0

**Comment by fuergaosi233** [comment]
I found the cause of the problem and it was caused by an upgrade to fastify
<img width="892" alt="image" src="https://user-images.githubusercontent.com/22197568/196716899-27b1338d-f6cd-4185-ad80-20c87c7cc729.png">
@soedirgo

**Comment by fuergaosi233** [comment]
And I think PostgresMeta needs e2e testing

**Comment by soedirgo** [comment]
Yeah, I mistakenly thought Fastify v4 has no breaking changes from the announcement blog post.

> And I think PostgresMeta needs e2e testing

Yes, definitely. There has been many cases where typecheck failures went unnoticed until actually running queries against the server (the tests only cover the `lib`). Unfortunately I'm a bit swamped right now - instead I'll just add a typecheck test in CI, which would've caught most of these cases. I'll convert the lib tests to server tests at some point.
