### ISSUE TITLE
Support composite types

### ISSUE THREAD

**Issue by hmnd** [supabase/postgres-meta#399]
# Feature request

## Is your feature request related to a problem? Please describe.

TypeScript type generation does not currently support custom data types. This is particularly an issue for me because it results in my function having an 'unknown' return type instead of my custom data type.

## Describe the solution you'd like

Support for custom data types in generated TypeScript types.

## Additional context

Example data type I have as the return type of my function:
```sql
CREATE TYPE autocomplete_result as (
   id text,
   label text,
   similarity real
);
```

**Comment by Davepar** [comment]
Related bug: https://github.com/supabase/cli/issues/686
