### ISSUE TITLE
typescript generated type of pgvector/vector is string

### ISSUE THREAD

**Issue by dejoma** [supabase/postgres-meta#578]
Enable Vector Extension in public schema, then create a table:

```SQL
create table dejoma_test (
  id serial primary key,
  title text not null,
  body text not null,
  embedding vector(1536)
);
```

Then execute:
`supabase gen types typescript --schema "public" --linked > example.ts`

To find that:
```typescript
dejoma_test: {
        Row: {
          body: string
          embedding: string | null
          id: number
          title: string
        }
        Insert: {
          body: string
          embedding?: string | null
          id?: number
          title: string
        }
        Update: {
          body?: string
          embedding?: string | null
          id?: number
          title?: string
        }
      }
```
which then in turn get's flagged by my typescript server:  
<img width="554" alt="image" src="https://github.com/supabase/supabase/assets/48984220/868bc089-4de4-4cff-ac11-64aa7e3d6219">

Please help, I (expect) that I can fix this locally by changing those types to `number[]` after generating the fles.

**Comment by soedirgo** [comment]
@dejoma you can also try the workaround [here](https://github.com/supabase/postgrest-js/issues/437#issuecomment-1590624310) - you can still use JSON number arrays to insert values into the column, but for fetching data you'll want to use a computed column so you don't have to cast all the time.

**Comment by soedirgo** [comment]
Closing this unless a better solution comes up for handling `vector` types

**Comment by galer7** [comment]
In case anyone is still interested, I came up with a workaround for this issue. You can find it in the [TS playground](https://www.typescriptlang.org/play?#code/FAehAIFEA8EMFsAOAbApuA5qgdqgTrAC6oAm4hAnougGZ4D284AzgK6KwBGsz6AFG2p5w8AJbZRNUaQCUwStXAARIlx7oAvOADewcOEStOyUQGMAXDr37wAMVbZThUfWzNLumzayEA+nlQ0ADdYbD8SelN3Ky8vAEE8DGjPWK8wO3phZkZ0AJ5XFnY1XnAAd1FkZEwcfCJ0ZkI8cQxwGkzwINQnTL4ZcipUa1T9Tu68Swam7AwAbiHh9IA6ZfmvAF854fAAJVRCVjw3D1XY9IBNegPWhycXbHAA-cP+xQALfEGt-SWVrbWAbQAuptYht5mD9GC1sBQBAABKBITXRzOVzMeQDcAAYVeoSwtmkyBIzAAPAAVAA0OwAfOAtAB5MSEclUgDWqAo9BoNPAADIdnMFOgcXjUAAFDD2FF3MkDEm2bAAOQQ6FQ0GI2GJLEazSpZNpWhF01QBMCxJJ1hUhGKqAp1hS+kMxjMliN+MJ5pOVpt-wA5E6TKZfYC7altHYbqijtjccbTUTSd7uLw-QGzMG-VLbmjg1Tw-92RRwOI7EqVYDLGTwGtadCvNSQdCGzD0hLkdn7pzWGVQoRyPRWqJoBjFABZIimV5KSKseA4QjMBXKud08C+nz+QKoEJhXwRKK+wWYgDiNQIxBI48Ik+npln88X2Flii0SfUqaMgYzvqzUeYGavG8ZznMJH2XVBgRHdBAKnYCHwVZ9NHARlRGZU9cHPUgYNve9QIQgYqV9BIkl9Wl+RSYjohQtCzzqS8J1gu8QIXfDqD9SjczXABHVh8AoXxUHgThSBIZpSL5HRwB4viBKEkTmksbBZ2EvAgWrOYwVhOwh3AEhVGTdAhSg8BEIAZVgGhUDfEpDVjLAJV-GU5V9eAGL3ODQN9KlsI8linwGZstMVehSnALtwFMUJdPoZZFmAUQkEyPtw1MPJiCxEx52rVoGCYX0AAFBBtEAioMgBaAArf85mAUw0T7A4qi0X1TIAVTFOIACE4lMyBfFa7YABlD1q+rwELVcWvarqer6gBpSAzhG0a3D7UxMrCVdUtQOoMukMJyQGczLOs1BqT4Rq2Q5GQZiAA)

**Comment by ekimcem** [comment]
Do we have to create vector db like this; ?

`create table dejoma_test (
  id serial primary key,
  title text not null,
  body text not null,
  embedding vector(1536)
);`

cant we assign the type from table UI ?

**Comment by maparent** [comment]
@galer7, I liked what you did, but I had two functions to change, so I went a step further.

https://gist.github.com/maparent/6af5c87c6297893d0d353d5ae47e0018

For the record, I am of the opinion that this is a bug and should be fixed.
