### ISSUE TITLE
Generate types for foreign tables

### ISSUE THREAD

**Issue by bastiaanv** [supabase/postgres-meta#579]
# Bug report

## Describe the bug

When running `Supabase gen typescript --db-url <URL> > database.ts` the tables that are connected via FDW to ClickHouse are not generating types

## To Reproduce

1. Setup FDW and create a ClickHouse handler. Then create a foreign table like this:
```sql
create foreign table glucose (
  timestamp timestamp,
  profile_id text,
  sensor_id text,
  glucose_mmol real,
  glucose_mg integer
)
  server clickhouse_server
  options (
    table 'glucose',
    rowid_column 'timestamp'
  );
```

2. First create docker image:
```bash
docker run -e PG_META_DB_URL=<URL> -it supabase/postgres-meta:v0.65.0 bash
```

3. Run generate types command:
```bash
node dist/server/app.js gen types typescript --include-schemas public > database.ts
```

4. Notice the foreign tables are not listed in the `database.ts`

## Expected behavior

To have all foreign tables to be listed

## System information

- OS: MacOS
- Version of Supabase-cli: 1.38.7
- Version of pgmeta: v0.65.0
- Version of Node.js: v19.6.1

**Comment by bastiaanv** [comment]
No I did not. Made the types myself

**Comment by codingisforlosers** [comment]
Upvoting!

**Comment by zgiuricich7** [comment]
Also running into this issue for the stripe wrapper integration.

**Comment by GportDev** [comment]
Also running into the same issue for stripe wrapper integration
