### ISSUE TITLE
Generating types for a postgresql array results in Typescript unknown property

### ISSUE THREAD

**Issue by tom-at-pixel** [supabase/postgres-meta#581]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Generating TypeScript types for a Supabase project is resulting in unexpected `unknown` properties. Specifically, any array type (e.g. `text[]`) generates `unknown` (instead of e.g. `string[]`).

## To Reproduce

1. Define any type with `text[]` in Supabase:

```sql
CREATE TYPE example_type AS (
  my_text_array text[]
);
```

2. Generate types in client project:

```
npx supabase gen types typescript --schema public
```

Observe the `unknown` property in the generated TypeScript types:

```ts
example_type: {
  my_text_array: unknown
}
```

## Expected behavior

I would expect a `string[]` property in the generated types:

```ts
example_type: {
  my_text_array: string[]
}
```

## System information

- OS: MAC OS
- Version of supabase CLI: 1.60.2

**Comment by mahendraHegde** [comment]
@tom-at-pixel  @gregnr  is this issue fixed already? i dont seem to be able to reproduce.

**Comment by tom-at-pixel** [comment]
@mahendraHegde Sorry for the delay in response. This is still an issue.

To repro, open a query editor in Supabase Studio and run this code:
```
CREATE TYPE test_array_type AS (
  my_text_array text[]
);
```

Then generate the types in the client:
```
npx supabase gen types typescript --schema public
```

The generated types include:
```
export interface Database {
  public: {
    CompositeTypes: {
      test_array_type: {
        my_text_array: unknown
      }
    }
  }
}
CompositeTypes: {
      playground_array_type: {
        my_text_array: unknown
      }
    }
```

**Comment by Theiaz** [comment]
I got the same problem, any updates?
