### ISSUE TITLE
Permission denied error when generating types

### ISSUE THREAD

**Issue by bombillazo** [supabase/postgres-meta#621]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We are getting a weird bug when running the type generation in github actions using the `supabase gen types typescript` command:

```
Status: Downloaded newer image for ghcr.io/supabase/postgres-meta:v0.68.0
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///usr/src/app/dist/server/server.js:58
        throw new Error(tablesError.message);
              ^

Error: permission denied for schema cron
    at file:///usr/src/app/dist/server/server.js:58:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `gen types typescript`

## Expected behavior

Supabase types are generated without a problem

## System information

- OS: ubuntu
- Version of supabase cli: 1.104.0
- Version of supabase-js: 2.38.0
- Version of Node.js: 18.16.0

**Comment by soedirgo** [comment]
Seems to be an issue with the project. Can you file a ticket on https://supabase.com/dashboard/support/new ?

**Comment by bombillazo** [comment]
Hey, it happens when running the commands from a GitHub actions with the `--local` flag, not in the remote :/

**Comment by bombillazo** [comment]
Seems like perhaps this was fixed in subsequent cli versions, but it is no longer an issue.
