### ISSUE TITLE
How to get online postgre-meta version?

### ISSUE THREAD

**Issue by S96EA** [supabase/postgres-meta#667]
I want support custom pg-meta image version using cli, [https://github.com/supabase/cli/issues/1702](1702), when I use local api endpoint, `http://127.0.0.1:54321/pg/`, the api returned success:
```
{"status":200,"name":"@supabase/postgres-meta","version":"0.0.0-automated","documentation":"https://github.com/supabase/postgres-meta"}
```

but when I call online endpoint, `https://my-project-xxxx.supabase.co/pg/`, there is no route matched:
```
{"message":"no Route matched with those values"}
```

how can I get the online postgre-meta version?

**Comment by soedirgo** [comment]
Hi! We don't currently expose the pg-meta version used in the backend, but we try to sync that with the version used in the latest CLI beta version. i.e. we upgrade the backend pg-meta first, and then bump the pg-meta version in the CLI shortly after.
