### ISSUE TITLE
Proposal/RFC: split up the API and the server

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres-meta#71]
At the moment all of the interactions work through an express server. However, when we start work on the CLI, we will need to use this functionality without express. My proposal is to split the API and Server functioanality into 2 areas

```bash
src
- api      # contains all the TypeScript classes
- server   # contains the express routes, which import from `../api`
```

Then, we should be able to do something this:

```sh
npm install @supabasee/pg-api
```

### API (usage with our CLI)

```js
import { createClient } from 'pg-api'

const api: PostgresApiClient = createClient(process.env.connection_string)

api.tables.add({
  schema: 'public',
  name: 'test'
})
```

### Server

```js
import { createServer } from  'pg-api'

const server: PostgresApiServer = createServer(process.env.connection_string, {})

server.start() // starts express server on port 3000
```

Then the route `POST /tables` calls `api.tables.add()`

**Comment by soedirgo** [comment]
Interesting, I suppose the API can be safely split off since the server is just for serving requests.

For making requests from the CLI, we can probably use [openapi-generator](https://github.com/OpenAPITools/openapi-generator) as @steve-chavez recommended [here](https://github.com/supabase/home/issues/19#issuecomment-650244642). Also, do we plan to use Node/TypeScript for the CLI?

**Comment by kiwicopple** [comment]
> do we plan to use Node/TypeScript for the CLI?
Yeah I had a play with Gluegun on the weekend and it seems like it could do the job. TBD though - I have only experimented with some small use-cases (generating TypeScript models/entities from the database).

**Comment by kiwicopple** [comment]
We have started this process here: https://github.com/supabase/pg-api/pull/87

And @soedirgo has outlined how it might look eventually here: https://github.com/soedirgo/postgres-meta

One thought: we have several functions like `getAll()`, `getById()`, `getByName()` etc. How would you feel about creating a common interface, where the `params` determine the private function: 

- list()
- retrieve(params) - For example, takes one of: `{ id?: number, name?: string }`
- create()
- update()
- remove()

**Comment by soedirgo** [comment]
I'm done refactoring the API to use the functions above (really liking `retrieve`, and TypeScript [supports function overloading](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads) apparently).

I'll try to finish this off tonight and run it through you tomorrow during cafe day. Sorry this took a while!

**Comment by w3b6x9** [comment]
@soedirgo 

> TypeScript [supports function overloading](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads)

This reminds me of Elixir's function arity. Very cool!
